@ShopApp_HostAddress = http://localhost:5170

# GET {{ShopApp_HostAddress}}/weatherforecast/
# Accept: application/json

###
POST /api/products
###
GET /api/products/4
###
PUT /api/products/4
###
GET /api/products/search?name=mon
###
DELETE /api/products/4
###
GET /api/products/4

